name = "how-connect-d1-with-remix"
compatibility_date = "2024-08-21"

[[d1_databases]]
binding = "DB"
preview_database_id = "bfdddaf0-00f7-42db-9b36-800284c3bf09"
database_name = "treefy-db"
database_id = "bfdddaf0-00f7-42db-9b36-800284c3bf09"
